name: azure pipeline
pool: myAgentPool
script: |
  #!/bin/bash
  echo hola mundo
  echo $(System.DefaultWorkingDirectory)
# trigger:
#   - main
# variables: 
#   home: $(System.DefaultWorkingDirectory) 
# pool: myAgentPool

# jobs:
# - job: PreWork
#   steps:
#   - task: CmdLine@2
#     inputs:
#       script: |
#         echo $(System.DefaultWorkingDirectory)
        
  # - task: PublishTestResults@2 
  #   displayName: Publicar los resultados
  #   inputs:
  #     testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
  #     testResultsFiles: '**/*.xml' 
  #     searchFolder: '$(home)/automatedtesting/postman/'
  #     #mergeTestResults: false # Optional
  #     #failTaskOnFailedTests: false # Optional
  #     testRunTitle: Postman Test
      # buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional