vm:	
	./create_vm.sh

image: 
	./create_image.sh

states: 
	./configure-tfstate-storage-account.sh

service_principal: 
	./create_sp.sh

info:
	echo "vm: creates a resourcegroup and vm\nimage: creates an image\nstates: configura storage-account for backend\nservice_principal: configure service principal" 