variable "username" {}
variable "location" {}
variable "resource_group" {}
variable "application_type" {}
variable "subnet_id" {}
variable "public_ip_address_id" {}
variable "resource_type" {}
variable "image_id" {}
variable "key" {}